trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    wget -O ~/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.deb
    sudo dpkg -i ~/hugo.deb
    hugo version
  displayName: 'Install hugo'

- script: |
    chmod +x ./build.sh
    ./build.sh
  displayName: 'Build'

- script: gulp deploy
  displayName: 'Deploy'
