language: ruby
rvm:
  - 2.2.5

dist: trusty
sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

script:
  - yarn build.prod
  - yarn global add gulp
  - yarn
  - gulp generate-sw
  - mv service-worker.js dist/
  - ls dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
