language: ruby
rvm:
  - 2.2.5

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

script:
  - gulp generate-sw
  - JEKYLL_ENV=production bundle exec jekyll build -d ./dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
