# Permalinks
permalink:           pretty

# Setup
title:               Hymns Repo
tagline:             'A catholic hymn repository'
description:         'A repository of hymns and songs used in catholic settings.'
baseurl:             ''
github:              'https://github.com/hymnsrepo/hymnsrepo-site'

# Hymns collection
collections:
  hymns:
    output:          true

defaults:
  - scope:
      path:            ""
      type:          hymns
    values:
      layout:        "hymn"
      subtitle:      ""
      title:         "Untitled"

gems: [jekyll-sitemap,jekyll-seo-tag]
exclude: [node_modules/, vendor/bundle]
