name: New hymn request
description: Request a hymn to be added to hymnsrepo.com
title: 'Hymn request: <hymn title>'
body:
  - type: input
    id: hymn-name
    attributes:
      label: Hymn title
      placeholder: Soul of my Savior
    validations:
      required: true
  - type: textarea
    id: hymn-lyrics
    attributes:
      label: Lyrics
      description: >-
        Enter the hymn lyrics here. Only hymns appropriate for Catholic services
        are accepted.
      value: |-
        Soul of my Savior sanctify my breast,
        Body of Christ, be thou my saving guest,
        Blood of my Savior, bathe me in thy tide,
        wash me with waters gushing from thy side.

        Strength and protection may thy passion be,
        O blessed Jesus, hear and answer me;
        deep in thy wounds, Lord, hide and shelter me,
        so shall I never, never part from thee.

        Guard and defend me from the foe malign,
        in death's dread moments make me only thine;
        call me and bid me come to thee on high
        where I may praise thee with thy saints for ay.
      render: md
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: Include any other information here

