name: Submit alternate lyrics
description: Submit alternate lyrics for an existing hymn.
title: 'Alternate lyrics: <hymn title>'
body:
  - type: input
    id: hymn-link
    attributes:
      label: Hymn link
      description: hymnrepo.com link to the existing hymn
      placeholder: https://hymnsrepo.com/hymns/soul-of-my-saviour/
    validations:
      required: true
  - type: textarea
    id: hymn-lyrics
    attributes:
      label: Alternate lyrics
      description: >-
        Enter the alternate lyrics. Only hymns appropriate for catholic services
        are accepted.
      value: |-
        Soul of my Savior sanctify my breast,
        Body of Christ, be thou my saving guest,
        Blood of my Savior, bathe me in thy tide,
        wash me with waters gushing from thy side.

        Strength and protection may thy passion be,
        O blessed Jesus, hear and answer me;
        deep in thy wounds, Lord, hide and shelter me,
        so shall I never, never part from thee.

        Guard and defend me from the foe malign,
        in death's dread moments make me only thine;
        call me and bid me come to thee on high
        where I may praise thee with thy saints for ay. 
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: Include any other information here

